### ISSUE TITLE
Installing panel in Grafana 5.2.1 not showing

### ISSUE THREAD

**Issue by lonelobo0070** [ryantxu/ajax-panel#12]
I installed the plugin in our Grafana 5.2.1 installation but after a restart of Grafana the panel is not shown in the list of panels.

**Comment by ryantxu** [comment]
When grafana-labs starts, you should see in the logs info as it loads plugins... Let me know what that says.  Either the plug-in is not installed, or the log will say something

**Comment by lonelobo0070** [comment]
In the logs it shows
`t=2018-07-13T07:25:05+0200 lvl=info msg="Registering plugin" logger=plugins name=AJAX`

Also in the plugin page of Grafana it is shown in the installed plugins section.
But no AJAX panel in the 'add panel' section.

**Comment by vmario89** [comment]
I had the same problem but upgrading to 5.2.2 solved the problem

**Comment by ryantxu** [comment]
I'll reopen if you still see this with recent versions
