### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by ivanB1975** [ryantxu/ajax-panel#18]
Is there a way to add CORS support to the GET requests? Other than using a proxy. I am using a node.js proxy to enrich the GET request with the CORS headers and this works. But I was wondering if there is an official way to do this.

**Comment by ryantxu** [comment]
The only way around  CORS is changing the headers on the server.  Your options are most likely:

1. use grafana proxy
2. some proxy like https://cors-anywhere.herokuapp.com/
