### ISSUE TITLE
Iterating through response object

### ISSUE THREAD

**Issue by codepattern** [ryantxu/ajax-panel#23]
Hi there,

Question - are you able to iterate (loop) through the response object using the angular template?  Current our data looks like 
[
 { "test": 1 },
 { "test": 2 }
]
and I want to display it using a template like:
<div> {{ response.test }} </div>

How can we perform this function?

**Comment by johntdyer** [comment]
+1

**Comment by johntdyer** [comment]
I am trying using some examples from the [Angular docs](https://angular.io/guide/template-syntax#template-input-variables) but its not working

```
<div *ngFor="let hero of heroes">{{hero.name}}</div>
<app-hero-detail *ngFor="let hero of heroes" [hero]="hero"></app-hero-detail>
```

 I would certainly appreciate any guidance you can provide

**Comment by ryantxu** [comment]
I'll update the example to something more interesting, but try:
```
<h2>Instance: {{ response.DEFAULT.instance_name }}</h2>

<div ng-repeat="(key, value) in response">
  <h5>{{key}}</h5>
  <pre>{{ value | json }}</pre>
</div>
```

Note this is angular 1.0 and any directive needs to be registered already in grafana.  either though a plugin or native.  I would not expect `<app-hero-detail` to do anything unless you did some other magic
