### ISSUE TITLE
Proper releases planned ? 

### ISSUE THREAD

**Issue by johntdyer** [ryantxu/ajax-panel#47]
Hello,
  
   
are there any plans to implement proper releases / versions on Github  ? Appears there is only 0.0.6 on Github.com and Grafana lists 0.0.7-dev and it seems like there is a pretty decent velocity of commits between them... 

Thanks !

**Comment by ryantxu** [comment]
most of the commits have been around using a new build tool/system [(@grafana/toolkit)](https://github.com/grafana/grafana/tree/master/packages/grafana-toolkit)... not much "real" development.  If there is anything urgent, let me know and we can push a release
