### ISSUE TITLE
Text style options

### ISSUE THREAD

**Issue by PhillippOhlandt** [ryantxu/ajax-panel#5]
Hey,

it would be nice if we had more control over the text that is displayed. Things like font size, color and position would be enough for the start I guess. I want mine to look the same as the Singlestat panel.

**Comment by PhillippOhlandt** [comment]
Since the current version supports custom templates, this can be seen as resolved.

**Comment by johntdyer** [comment]
@PhillippOhlandt  - how can I find more info on using this template feature ?

**Comment by ryantxu** [comment]
The the angular template in the `Examples` tab.  there is not any real documentation, just examples and source code 😄
