### ISSUE TITLE
HTTP Error (404) Not Found

### ISSUE THREAD

**Issue by vmadman** [ryantxu/ajax-panel#6]
When updating the plugin using the grafana-cli utility, everything broke, and Grafana shows `HTTP Error (404) Not Found" whenever I load a dashboard that has an Ajax panel on it.

```
Request URL: http://grafana.mycompany/public/plugins/ryantxu-ajax-panel/module.html?v=1524046009100
Request Method: GET
Status Code: 404 Not Found
Remote Address: 10.0.99.99:80
Referrer Policy: no-referrer-when-downgrade
```

It makes me wonder if I need to update Grafana, but idk...

```
Grafana v5.0.0-beta5 (commit: c21d9de) 
```

**Comment by ryantxu** [comment]
Can you try a full refresh -- make sure you are not getting cached javascript?

the URL should now be `partials/module.html` unless the javascript is old.

See:
https://github.com/grafana/grafana/issues/11446

**Comment by ryantxu** [comment]
The 404 should be fixed in latest grafana release.  Note this is really a browser cache issue, not an issue with this plugin
