### ISSUE TITLE
Problems with Grafana 5.1

### ISSUE THREAD

**Issue by chrw** [ryantxu/ajax-panel#7]
We updated Grafana to 5.1 recently and had problems using a simple text query. I have no clue why it's not working. I tried to clean my browser caches, etc. but with no luck. We did a revert to Grafana 5.0.4 and it worked again.

Did you have the chance to have a look at Grafana 5.1?

Thanks. And also thank you for the plugin. 👍

**Comment by ryantxu** [comment]
The issue was with the scrollbar library that got added in 5.1 😢 

Simple fix is added to master and will be released soon.

**Comment by chrw** [comment]
Awesome! Thanks for the fast fix! 👍 Looking forward to the next release.

**Comment by mpsmith** [comment]
+1 looking forward to the release.
