### ISSUE TITLE
The plugin is unsigned

### ISSUE THREAD

**Issue by HenrikRolandHansen** [ryantxu/ajax-panel#74]
Grafana Labs can’t guarantee the integrity of this unsigned plugin Is it possible for the plugin to be signed?

**Comment by DetroitSteelTreating** [comment]
I also want very much to use this plug in, but Grafana Labs will not let me because it is unsigned.  Any reason why this cannot be done?  FWIW, I am using Grafana Cloud v7.3.6

Thank you for developing this plug in!

**Comment by moorchegue** [comment]
With Grafana 8 it's now impossible to use the plugin because it's not signed. Is there any known workaround or an alternative?

**Comment by HenrikRolandHansen** [comment]
I just testet Grafana 8.0.1 with latest ajax plugin and the plugin seams to be signed and working fine. 

Try to delete the old ajax plugin folder and install latest version with grafana-cli or manual.
