### ISSUE TITLE
Support empty text response

### ISSUE THREAD

**Issue by PhillippOhlandt** [ryantxu/ajax-panel#9]
Hello,

my "Text" panel loads an URL that either returns text or an empty response (empty string).

Today, I updated to the current version of Grafana and this plugin and in case I get an empty string as response, the panel shows `[object Object]` via the "Direkt HTML" mode.

Then I switched to "Angular Template" and saw that the `response` variable is an object with `{"data":"","status":200, ...}`.

I changed the template to use `response.data` and it looked fine (empty panel), but now those panels who should contain text are empty too. It turned out that the `response` variable for those panels contain the text returned by the URL and therefore there is no `response.data`.

Conclusion:

Empty response: `response` contains object
Non-empty response: `response` contains the text

It would be nice if it would have consistent behavior.

**Comment by ryantxu** [comment]
supported in latest master
