### ISSUE TITLE
Sign Plugin for Grafana 8.x

### ISSUE THREAD

**Issue by mhollstein** [ryantxu/ajax-panel#90]
Since Grafana 8.x plugins should be signed. Can you sign your plugin for Grafana 8, please?

https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/
https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/

Best Regards, Michael

**Comment by HenrikRolandHansen** [comment]
in my version 8.0.1 the plug-in is signed ![image](https://user-images.githubusercontent.com/8969659/122607329-aeab9500-d07a-11eb-902e-7a397ea90110.png)

Try to delete Old plug-in folder and install latest version

**Comment by mhollstein** [comment]
Update doesn't work. After deleting the old one and installing the new one, everything works fine. It is signed now. Thanks.
